[Interface]
PrivateKey = 6JJKNPsnxNJBAR5CK00HmzlrwuhdaT+n5HbueONv2Xs=
Address = 10.66.66.2/24
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = nfBmt/np9emFu/pWtM+n2rQynJz429K+Hl1+fCCakGo=
PresharedKey = qGQWSfHBsHWVFDV3X+ajE1b/tA+DvO96E32y+XVkIOU=
Endpoint = 34.180.46.55:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
